on: 
    issues:
        types: [opened, edited, milestoned]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
 #   steps:
  #  - name: GitHub Contribution Report Generator
#      uses: ros-tooling/github-contribution-report-generator@0.0.7
    steps:
    - uses: ros-security/github-contribution-report-generator@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        since-n-days-ago: 7
        authors-filter: |
          thomas-moulard
        organizations-filter: |
          ros-security    
        file-name: |
            rreport
